config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :interviews
  resources :participants
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/home' => 'interviews#home'
  root 'interviews#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interview.rb
class Interview < ApplicationRecord
    has_many :sessions, dependent: :destroy
    has_many :participants, through: :sessions
    has_attached_file :resume

    validates_attachment :resume, presence: true,
    content_type: { content_type: ["application/pdf"] }
end

app/models/participant.rb
class Participant < ApplicationRecord
    has_many :sessions
    has_many :interviews, through: :sessions, dependent: :delete_all
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :interview
  belongs_to :participant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_forgery_protection
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  def home
    @interviews = Interview.all
    render json: @interviews
  end

  def index
    @interviews = Interview.all  
  end

  def create
    @interview = Interview.new(interview_params)
    if @interview.save
      render json: {
        :success => true
      }
    else
      render json: {
        :success => false
      }
    end
  end

  def new
    @interview = Interview.new
  end

  def edit
  end

  def show
    @interview = Interview.find(params[:id])
    render json: {
      :interview => @interview,
      :participants => @interview.participants
    }
  end

  def destroy
    @interview = Interview.find(params[:id])
    @interview.destroy
    # redirect_to :action =>'index'
  end

  def update
    @interview.update(interview_params)
    UpdateInterviewWorker.perform_async(@interview.id)
    ReminderWorker.perform_at(@interview.start_time - 30.minutes, @interview.id)
    # redirect_to :action =>'index'
  end

  private
    def set_interview
      @interview = Interview.find(params[:id])
      @participants = @interview.participants
      @participant = Participant.new
    end
    
    def interview_params
      params.require(:interview).permit(:title, :start_time, :end_time, :resume)
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  def index
    @participants = Participant.all
    render json: @participants
  end

  def create
    
    @participant = Participant.find_by_email(params[:participant][:email])
    if @participant == nil
      @participant = Participant.create(create_participant_params)
    end
    @interview = Interview.find(params[:participant][:interview_id])
    
    isValid = true
    for i in @participant.interviews do 
      if (@interview.start_time <= i.start_time) && (i.start_time <= @interview.end_time)
        isValid = false
      elsif (@interview.start_time <= i.end_time) && (i.end_time <= @interview.end_time)
        isValid = false
      end
    end

    if isValid
      NewInterviewWorker.perform_async(params[:participant][:email], params[:participant][:interview_id])
      SingleReminderWorker.perform_at(@interview.start_time - 30.minutes, @participant.email)
        
      @interview.participants<< (@participant)
      @participant.interviews<< (@interview)
    else 
      redirect_to root_path, notice: "The participant has clashing schedule"
    end
  end

  def new
    @participant = Participant.new
  end

  def edit
  end

  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy
    redirect_to root_path
  end

  def update
    @participant.update(participant_params)
    redirect_to :action =>'index'
  end

  private
    def set_participant
      @participant = Participant.find(params[:id])
    end

    def create_participant_params
      params.require(:participant).permit(:email, :role)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/interviews/_form.html.erb
<%= form_with(model: interview, local: true) do |form| %>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :start_time %>
        <%= form.datetime_field :start_time %>
    </div>
    <div class="field">
        <%= form.label :end_time %>
        <%= form.datetime_field :end_time %>
    </div>
    <div class="field">
        <%= form.label :resume %>
        <%= form.file_field :resume %>
    </div> 
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/interviews/create.html.erb
<h1>Interviews#create</h1>
<p>Find me in app/views/interviews/create.html.erb</p>

app/views/interviews/edit.html.erb
<%= render 'form', interview: @interview %>

app/views/interviews/index.html.erb
<div id="header_container"></div>

<div id="page_container" class="container pageEntry"></div>

app/views/interviews/new.html.erb
<%= render 'form', interview:@interview %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Interviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start Time</th>
      <th>End Time </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @interview.title %></td>
        <td><%= @interview.start_time %></td>
        <td><%= @interview.end_time %></td>
      </tr>
  </tbody>
</table>

<h1>Participants</h1>
<table>
  <thead>
    <tr>
      <th> Email </th>
      <th> Role </th>
    </tr>
  </thead>

  <tbody>
    <% @interview.participants.each do |participant| %>
      <tr>
        <td><%= participant.email %></td>
        <td><%= participant.role %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1> Add participants </h1>
<%= form_with(model: @participant, local: true) do |form| %>
    <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>
    <div class="field">
        <%= form.label :role %>
        <%= form.text_field :role %>
    </div>
    <%= form.hidden_field :interview_id, value: @interview.id %>
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

<br>

<%= link_to 'All Interviews', interviews_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hasmanylearn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://blackrockdigital.github.io/startbootstrap-bare/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/participants/_form.html.erb
<%= form_with(model: participant, local: true) do |form| %>
    <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/participants/create.html.erb
<h1>Participants#create</h1>
<p>Find me in app/views/participants/create.html.erb</p>

app/views/participants/edit.html.erb
<%= render 'form', participant: @participant %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"> Email </th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.email %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<%= render 'form', participant:@participant %>